### ISSUE TITLE
Remote demo videos not working

### ISSUE THREAD

**Issue by jaruba** [maaAnandsheela/beeg-stremio-addon#1]
As the title says, all videos seem to be a short video commercial for the website.

**Comment by maaAnandsheela** [comment]
I don't get the issue can you provide screenshot or remote link for this issue.

Can you please provide info on which stremio platform you tested.?

**Comment by jaruba** [comment]
I tested on the [web version](http://app.strem.io/shell-v4.4/#/), and all videos were the same 10 sec video saying "Moved to beeg".

It does seem to work in the desktop app though now that i've tested again. I doubt the streams can be fixed to work with the web version, so I'm closing this.

**Comment by maaAnandsheela** [comment]
hi jaruba

I was familiar with this issue. Thats why I have already mentioned it in readme for web version. But i think i can make it as external url only for web version.

**Comment by jaruba** [comment]
Srry for not paying closer attention to the readme, you did indeed state that it's a known issue.

I'm used to videos just giving errors in the web version, when i saw the videos replaced with some commercial I presumed it's like that everywhere.

It was my mistake, it's normal for some streams to not be supported in the web version.
