### ISSUE TITLE
This add-on no longer works either

### ISSUE THREAD

**Issue by danamag** [maaAnandsheela/beeg-stremio-addon#2]
😄

**Comment by maaAnandsheela** [comment]
Hi thanks for the issue. I ll look into it and update the addon according to new beeg setup.

**Comment by maaAnandsheela** [comment]
Hi. I have fixed streams and images and updated to latest beeg setup check and confirm.

**Comment by danamag** [comment]
it works great now, thanks so much for fixing it!
